### PR TITLE
[macOS] Use notarytool instead of deprecated altool.

### PR DESCRIPTION
**Pull request by bruvzg**

### CODE REVIEW

**Comment by bruvzg** [comment]
Completely forgot about this, `altool` is deprecated and will spot working in November, so this change will be necessary to notarize official builds.

This need to be tested with real Apple ID (I do not have one), note the new required `APPLE_TEAM` config variable (see [Locate your Team ID](https://developer.apple.com/help/account/manage-your-team/locate-your-team-id)).

**Comment by akien-mga** [comment]
I've tested this, I'm getting this error:
```
Godot_v4.2-beta4_macos.universal.zip                                                                                                                                                            100%   84MB 111.7MB/s   00:00    
editor.entitlements                                                                                                                                                                             100%  654     1.4MB/s   00:00    
Archive:  Godot_v4.2-beta4_macos.universal.zip
   creating: Godot.app/
   creating: Godot.app/Contents/
  inflating: Godot.app/Contents/Info.plist  
 extracting: Godot.app/Contents/PkgInfo  
   creating: Godot.app/Contents/Resources/
   creating: Godot.app/Contents/Resources/ar.lproj/
 extracting: Godot.app/Contents/Resources/ar.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/fa.lproj/
 extracting: Godot.app/Contents/Resources/fa.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ko.lproj/
 extracting: Godot.app/Contents/Resources/ko.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/si.lproj/
 extracting: Godot.app/Contents/Resources/si.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/zh_CN.lproj/
 extracting: Godot.app/Contents/Resources/zh_CN.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/es_AR.lproj/
 extracting: Godot.app/Contents/Resources/es_AR.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ja.lproj/
 extracting: Godot.app/Contents/Resources/ja.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/pt_BR.lproj/
 extracting: Godot.app/Contents/Resources/pt_BR.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/uk.lproj/
 extracting: Godot.app/Contents/Resources/uk.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/sv.lproj/
 extracting: Godot.app/Contents/Resources/sv.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/or.lproj/
 extracting: Godot.app/Contents/Resources/or.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/en.lproj/
 extracting: Godot.app/Contents/Resources/en.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ka.lproj/
 extracting: Godot.app/Contents/Resources/ka.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/bn.lproj/
 extracting: Godot.app/Contents/Resources/bn.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/fr.lproj/
 extracting: Godot.app/Contents/Resources/fr.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/mi.lproj/
 extracting: Godot.app/Contents/Resources/mi.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/sq.lproj/
 extracting: Godot.app/Contents/Resources/sq.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/br.lproj/
 extracting: Godot.app/Contents/Resources/br.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ga.lproj/
 extracting: Godot.app/Contents/Resources/ga.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/mk.lproj/
 extracting: Godot.app/Contents/Resources/mk.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/sr-Cyrl.lproj/
 extracting: Godot.app/Contents/Resources/sr-Cyrl.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/az.lproj/
 extracting: Godot.app/Contents/Resources/az.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/fi.lproj/
 extracting: Godot.app/Contents/Resources/fi.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/lt.lproj/
 extracting: Godot.app/Contents/Resources/lt.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/sk.lproj/
 extracting: Godot.app/Contents/Resources/sk.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/zh_HK.lproj/
 extracting: Godot.app/Contents/Resources/zh_HK.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/tr.lproj/
 extracting: Godot.app/Contents/Resources/tr.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/id.lproj/
 extracting: Godot.app/Contents/Resources/id.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/et.lproj/
 extracting: Godot.app/Contents/Resources/et.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/lv.lproj/
 extracting: Godot.app/Contents/Resources/lv.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/da.lproj/
 extracting: Godot.app/Contents/Resources/da.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/hi.lproj/
 extracting: Godot.app/Contents/Resources/hi.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ms.lproj/
 extracting: Godot.app/Contents/Resources/ms.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ta.lproj/
 extracting: Godot.app/Contents/Resources/ta.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/sr-Latn.lproj/
 extracting: Godot.app/Contents/Resources/sr-Latn.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ro.lproj/
 extracting: Godot.app/Contents/Resources/ro.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ur_PK.lproj/
 extracting: Godot.app/Contents/Resources/ur_PK.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/bg.lproj/
 extracting: Godot.app/Contents/Resources/bg.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/fil.lproj/
 extracting: Godot.app/Contents/Resources/fil.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/mr.lproj/
 extracting: Godot.app/Contents/Resources/mr.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/eo.lproj/
 extracting: Godot.app/Contents/Resources/eo.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/is.lproj/
 extracting: Godot.app/Contents/Resources/is.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/pl.lproj/
 extracting: Godot.app/Contents/Resources/pl.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/tt.lproj/
 extracting: Godot.app/Contents/Resources/tt.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/de.lproj/
 extracting: Godot.app/Contents/Resources/de.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/hr.lproj/
 extracting: Godot.app/Contents/Resources/hr.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/nb.lproj/
 extracting: Godot.app/Contents/Resources/nb.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/te.lproj/
 extracting: Godot.app/Contents/Resources/te.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ca.lproj/
 extracting: Godot.app/Contents/Resources/ca.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/gl.lproj/
 extracting: Godot.app/Contents/Resources/gl.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ml.lproj/
 extracting: Godot.app/Contents/Resources/ml.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/es.lproj/
 extracting: Godot.app/Contents/Resources/es.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/it.lproj/
 extracting: Godot.app/Contents/Resources/it.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/pt.lproj/
 extracting: Godot.app/Contents/Resources/pt.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/tzm.lproj/
 extracting: Godot.app/Contents/Resources/tzm.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/el.lproj/
 extracting: Godot.app/Contents/Resources/el.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/hu.lproj/
 extracting: Godot.app/Contents/Resources/hu.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/nl.lproj/
 extracting: Godot.app/Contents/Resources/nl.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/th.lproj/
 extracting: Godot.app/Contents/Resources/th.lproj/InfoPlist.strings  
  inflating: Godot.app/Contents/Resources/Shader.icns  
  inflating: Godot.app/Contents/Resources/Scene.icns  
  inflating: Godot.app/Contents/Resources/Resource.icns  
   creating: Godot.app/Contents/Resources/sl.lproj/
 extracting: Godot.app/Contents/Resources/sl.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/zh_TW.lproj/
 extracting: Godot.app/Contents/Resources/zh_TW.lproj/InfoPlist.strings  
  inflating: Godot.app/Contents/Resources/GDScript.icns  
  inflating: Godot.app/Contents/Resources/Godot.icns  
  inflating: Godot.app/Contents/Resources/Project.icns  
   creating: Godot.app/Contents/Resources/cs.lproj/
 extracting: Godot.app/Contents/Resources/cs.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/he.lproj/
 extracting: Godot.app/Contents/Resources/he.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/af.lproj/
 extracting: Godot.app/Contents/Resources/af.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/eu.lproj/
 extracting: Godot.app/Contents/Resources/eu.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/km.lproj/
 extracting: Godot.app/Contents/Resources/km.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/ru.lproj/
 extracting: Godot.app/Contents/Resources/ru.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/Resources/vi.lproj/
 extracting: Godot.app/Contents/Resources/vi.lproj/InfoPlist.strings  
   creating: Godot.app/Contents/MacOS/
  inflating: Godot.app/Contents/MacOS/Godot  
Godot.app: signed app bundle with Mach-O universal (x86_64 arm64) [org.godotengine.godot]
  adding: Godot.app/ (stored 0%)
  adding: Godot.app/Contents/ (stored 0%)
  adding: Godot.app/Contents/_CodeSignature/ (stored 0%)
  adding: Godot.app/Contents/_CodeSignature/CodeResources (deflated 94%)
  adding: Godot.app/Contents/MacOS/ (stored 0%)
  adding: Godot.app/Contents/MacOS/Godot (deflated 59%)
  adding: Godot.app/Contents/Resources/ (stored 0%)
  adding: Godot.app/Contents/Resources/de.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/de.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/he.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/he.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ar.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ar.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/el.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/el.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ja.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ja.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/mi.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/mi.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/Resource.icns (deflated 18%)
  adding: Godot.app/Contents/Resources/fa.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/fa.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/mr.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/mr.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/sr-Cyrl.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/sr-Cyrl.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/Shader.icns (deflated 38%)
  adding: Godot.app/Contents/Resources/mk.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/mk.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/sq.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/sq.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/eu.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/eu.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/en.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/en.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/uk.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/uk.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/zh_CN.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/zh_CN.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/nb.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/nb.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/es.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/es.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/is.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/is.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/sl.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/sl.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/or.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/or.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/pt_BR.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/pt_BR.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/da.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/da.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/gl.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/gl.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/eo.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/eo.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/et.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/et.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/it.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/it.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/bg.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/bg.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/sk.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/sk.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/sr-Latn.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/sr-Latn.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/Godot.icns (deflated 13%)
  adding: Godot.app/Contents/Resources/ms.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ms.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/si.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/si.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ta.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ta.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ml.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ml.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/sv.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/sv.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/te.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/te.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/cs.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/cs.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/km.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/km.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ko.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ko.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/tzm.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/tzm.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/fil.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/fil.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/hu.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/hu.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/zh_HK.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/zh_HK.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ka.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ka.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/Project.icns (deflated 16%)
  adding: Godot.app/Contents/Resources/ga.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ga.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/tr.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/tr.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/pl.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/pl.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/zh_TW.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/zh_TW.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/br.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/br.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/vi.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/vi.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/lv.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/lv.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/lt.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/lt.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ru.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ru.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/af.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/af.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/tt.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/tt.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/fr.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/fr.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/fi.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/fi.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/id.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/id.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/nl.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/nl.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/th.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/th.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/az.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/az.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/GDScript.icns (deflated 17%)
  adding: Godot.app/Contents/Resources/pt.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/pt.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/Scene.icns (deflated 40%)
  adding: Godot.app/Contents/Resources/bn.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/bn.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ro.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ro.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ur_PK.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ur_PK.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/hr.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/hr.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/hi.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/hi.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/ca.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/ca.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Resources/es_AR.lproj/ (stored 0%)
  adding: Godot.app/Contents/Resources/es_AR.lproj/InfoPlist.strings (stored 0%)
  adding: Godot.app/Contents/Info.plist (deflated 81%)
  adding: Godot.app/Contents/PkgInfo (stored 0%)
Error: 2 unexpected arguments: 'path:', '/var/folders/1f/dm6_r2hs6dv4ly8dnsmx0cl80000gn/T/tmp.2j8fKQdH1J/Godot_v4.2-beta4_macos.universal_signed.zip'
Usage: notarytool global-options app-store-connect-options app-specific-password-options keychain-options credential-options output-options wait-options wait [<options>] <submission-id>
  See 'notarytool global-options app-store-connect-options app-specific-password-options keychain-options credential-options output-options wait-options wait --help' for more information.
Notarization failed.
Error: Unexpected argument '/var/folders/1f/dm6_r2hs6dv4ly8dnsmx0cl80000gn/T/tmp.2j8fKQdH1J/Godot_v4.2-beta4_macos.universal_signed.zip'
Usage: notarytool global-options app-store-connect-options app-specific-password-options keychain-options credential-options output-options log [<options>] <submission-id> <output-path>
  See 'notarytool global-options app-store-connect-options app-specific-password-options keychain-options credential-options output-options log --help' for more information.
```

**Comment by akien-mga** [comment]
It works if I run the same command directly after ssh'ing to the Mac:
```
xcrun notarytool submit /var/folders/1f/dm6_r2hs6dv4ly8dnsmx0cl80000gn/T/tmp.2j8fKQdH1J/Godot_v4.2-beta4_macos.universal_signed.zip --team-id "${APPLE_TEAM}" --apple-id "${APPLE_ID}" --password "${APPLE_ID_PASSWORD}" --no-progress
```

So something must go wrong in trying to run that command via ssh directly.

**Comment by bruvzg** [comment]
> _request_uuid=$(echo ${_request_uuid} | grep 'id:' | sed -e 's/.*id: //')

Seems like it's getting some unnecessary part of output, so only `wait` and `log` fail.

**Comment by akien-mga** [comment]
We could consider refactoring to use `--wait`, from a quick test it seems to take 1 min here. But not sure how well that will behave at times where the process would be longer.

`--output-format` could likely be used too to get json or plist instead of the pretty printed output, so that the id is easier to extract.

**Comment by akien-mga** [comment]
This works on the JSON output, but there might be a more elegant way to do the same:
```
echo $_request_uuid | sed -e 's/.*"id":"\([^"]*\)".*/\1/'
```

**Comment by bruvzg** [comment]
> That adds a server side dependency but it's less hacky.

`jq` is not part of default macOS environment, so we probably should keep sed.

> We could consider refactoring to use --wait, from a quick test it seems to take 1 min here (including 20s to upload the file). But not sure how well that will behave at times where the process would be longer.

Probably won't have any difference, just make parsing both status and id from the same output more complex.

**Comment by bruvzg** [comment]
> jq is not part of default macOS environment, so we probably should keep sed.

Or I guess it's running on the other side, so it doesn't matter.

**Comment by akien-mga** [comment]
Tested successfully. Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for all supported branches (`4.1`, `4.0`, `3.x`, `3.5`).

**Pull request merged**
